// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnYGDaL86KpK-9xwA_pFj2u6pjQXjnS_k',
    appId: '1:720695532060:android:3c86971f9f297753dd5dd9',
    messagingSenderId: '720695532060',
    projectId: 'japaneseapplearning',
    storageBucket: 'japaneseapplearning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmTHW1YTNbA48KnFq7tgdU4vh2RNa4TN4',
    appId: '1:720695532060:ios:04cfc5677b9c6ce4dd5dd9',
    messagingSenderId: '720695532060',
    projectId: 'japaneseapplearning',
    storageBucket: 'japaneseapplearning.firebasestorage.app',
    iosClientId: '720695532060-uu9gut9uln382k0p6293cejc3ui4f5o7.apps.googleusercontent.com',
    iosBundleId: 'kiradev.studio.japaneseapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9EeBUTslEQDGzpe-Z0vCpkbjbTLHj80w',
    appId: '1:720695532060:web:7f29946f22369ce7dd5dd9',
    messagingSenderId: '720695532060',
    projectId: 'japaneseapplearning',
    authDomain: 'japaneseapplearning.firebaseapp.com',
    storageBucket: 'japaneseapplearning.firebasestorage.app',
    measurementId: 'G-HVZZMPQKPK',
  );

}